# Generated by Django 4.2 on 2024-07-05 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1', models.CharField(max_length=50, verbose_name='Команда 1')),
                ('team2', models.CharField(max_length=50, verbose_name='Команда 2')),
                ('score1', models.IntegerField(verbose_name='Счет 1')),
                ('score2', models.IntegerField(verbose_name='Счет 2')),
                ('date', models.DateTimeField(help_text='Московское время', verbose_name='Время проведения')),
            ],
            options={
                'verbose_name': 'матч',
                'verbose_name_plural': 'матчи',
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='TGUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, unique=True, verbose_name='Телеграм id')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ник телеграм')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя')),
                ('family_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создание аккаунта')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
            ],
            options={
                'verbose_name': 'отправитель',
                'verbose_name_plural': 'отправители',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Название чемпионата')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
                ('order', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'чемпионат',
                'verbose_name_plural': 'чемпионаты',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Название тура')),
                ('order', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Порядок')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='core.tournament')),
            ],
            options={
                'verbose_name': 'тур',
                'verbose_name_plural': 'туры',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Predict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score1', models.IntegerField(verbose_name='Счет 1')),
                ('score2', models.IntegerField(verbose_name='Счет 2')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создание прогноза')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновление прогноза')),
                ('points', models.IntegerField(blank=True, default=None, null=True, verbose_name='Баллы')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_predicts', to='core.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicts', to='core.tguser')),
            ],
            options={
                'verbose_name': 'матч',
                'verbose_name_plural': 'матчи',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='match',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='core.round'),
        ),
    ]
