# Generated by Django 4.2 on 2024-07-05 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_round_options_remove_round_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='score1',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Счет 1'),
        ),
        migrations.AlterField(
            model_name='match',
            name='score2',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Счет 2'),
        ),
    ]
