# Generated by Django 4.2 on 2024-07-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_match_score1_alter_match_score2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tguser',
            options={'ordering': ('-created_at',), 'verbose_name': 'пользователь', 'verbose_name_plural': 'пользователи'},
        ),
        migrations.RemoveField(
            model_name='tguser',
            name='family_name',
        ),
        migrations.AddField(
            model_name='round',
            name='finished',
            field=models.BooleanField(default=False, verbose_name='Завершен'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='finished',
            field=models.BooleanField(default=False, verbose_name='Завершен'),
        ),
    ]
