# Generated by Django 4.2 on 2024-07-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_tguser_options_remove_tguser_family_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predict',
            name='score1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Счет 1'),
        ),
        migrations.AlterField(
            model_name='predict',
            name='score2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Счет 2'),
        ),
    ]
