# Generated by Django 4.2 on 2024-07-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_predict_options_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rounds',
            field=models.ManyToManyField(to='core.round', verbose_name='Туры в рейтинге'),
        ),
    ]
