# Generated by Django 4.2 on 2024-07-07 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_rating_rounds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название тура'),
        ),
    ]
