# Generated by Django 4.2 on 2025-11-05 08:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_round_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaders_per_page', models.PositiveIntegerField(default=50, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)], verbose_name='Количество лидеров на странице')),
                ('domain', models.CharField(blank=True, max_length=200, null=True, verbose_name='Домен')),
            ],
            options={
                'verbose_name': 'базовые настройки',
                'verbose_name_plural': 'базовые настройки',
            },
        ),
    ]
